import {defineMessages} from "react-intl";

const names = defineMessages({
    auth: {defaultMessage: "Auth"},
    "auth.login": {defaultMessage: "Login"},
    "auth.register": {defaultMessage: "Register"},
    "auth.forgot-password": {defaultMessage: "Forgot Password"},
    user: {defaultMessage: "User"},
    "user.account": {defaultMessage: "Account"},
    "user.purchases": {defaultMessage: "Purchases"},
    admin: {defaultMessage: "Admin"},
    "admin.home": {defaultMessage: "Statistics"},
    "admin.users": {defaultMessage: "Users"},
    "admin.marketplace": {defaultMessage: "Marketplace"},
    "admin.wallets": {defaultMessage: "Wallets"},
    "admin.verification": {defaultMessage: "Verification"},
    "admin.payments": {defaultMessage: "Payments"},
    "admin.exchange": {defaultMessage: "Exchange"},
    "admin.giftcards": {defaultMessage: "Giftcards"},
    "admin.settings": {defaultMessage: "Settings"},
    "admin.localization": {defaultMessage: "Localization"},
    "admin.customize": {defaultMessage: "Customize"},
    "admin.developer": {defaultMessage: "Developer"},
    landing: {defaultMessage: "Landing"},
    home: {defaultMessage: "Home"},
    settings: {defaultMessage: "Settings"},
    help: {defaultMessage: "Help"},
    "user-setup": {defaultMessage: "User Setup"},
    wallets: {defaultMessage: "Wallets"},
    exchange: {defaultMessage: "Exchange"},
    "exchange.trade": {defaultMessage: "Trades"},
    "exchange.swap": {defaultMessage: "Swap"},
    giftcards: {defaultMessage: "Giftcards"},
    "giftcards.shop": {defaultMessage: "Shop"},
    "giftcards.checkout": {defaultMessage: "Checkout"},
    payments: {defaultMessage: "Payments"},
    limits: {defaultMessage: "Limits"}
});

export default names;
